In [1]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [2]:
df = pd.DataFrame([
    {"tempo_entrega": 25, "valor_pedido": 70, "tipo_entrega": "Moto"},
    {"tempo_entrega": 40, "valor_pedido": 40, "tipo_entrega": "Carro"},
    {"tempo_entrega": 30, "valor_pedido": 85, "tipo_entrega": "Bike"},
])

df

   tempo_entrega  valor_pedido tipo_entrega
0             25            70         Moto
1             40            40        Carro
2             30            85         Bike

In [3]:
num_cols = ["tempo_entrega", "valor_pedido"]
cat_cols = ["tipo_entrega"]

preprocessor = ColumnTransformer(
    transformers=[
        ("num", MinMaxScaler(), num_cols),
        ("cat", OneHotEncoder(handle_unknown="ignore", sparse_output=False), cat_cols)
    ]
)

X = preprocessor.fit_transform(df)
X

array([[0.        , 0.66666667, 0.        , 0.        , 1.        ],
       [1.        , 0.        , 0.        , 1.        , 0.        ],
       [0.33333333, 1.        , 1.        , 0.        , 0.        ]])

In [4]:
cat_encoder = preprocessor.named_transformers_["cat"]
cat_names = cat_encoder.get_feature_names_out(cat_cols).tolist()
feature_names = num_cols + cat_names

df_features = pd.DataFrame(X, columns=feature_names)

df_features

,tempo_entrega,valor_pedido,tipo_entrega_Bike,tipo_entrega_Carro,tipo_entrega_Moto
0,0.000000,0.666667,0.0,0.0,1.0
1,1.000000,0.000000,0.0,1.0,0.0
2,0.333333,1.000000,1.0,0.0,0.0